export enum ItemStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum Stage {
  NA_FILA = "NA_FILA",
  PRODUZINDO = "PRODUZINDO",
  EXPEDICAO = "EXPEDICAO",
  ENTREGUE = "ENTREGUE",
}
